import {
  Bell,
  Calendar,
  Camera,
  Check,
  Clipboard,
  Command,
  Copy,
  Download,
  Edit,
  Eye,
  FileText,
  Folder,
  Home,
  Image,
  Keyboard,
  Link,
  Lock,
  Mail,
  Mic,
  Pause,
  Play,
  Plus,
  RefreshCw,
  Save,
  Scissors,
  Search,
  Settings,
  Star,
  Terminal,
  Trash2,
  Upload,
  User,
  Volume2,
  type LucideIcon,
} from "lucide-react";

export const MACRO_ICON_OPTIONS = [
  { id: "bell", label: "Bell", icon: Bell },
  { id: "calendar", label: "Calendar", icon: Calendar },
  { id: "camera", label: "Camera", icon: Camera },
  { id: "check", label: "Check", icon: Check },
  { id: "clipboard", label: "Clipboard", icon: Clipboard },
  { id: "command", label: "Command", icon: Command },
  { id: "copy", label: "Copy", icon: Copy },
  { id: "download", label: "Download", icon: Download },
  { id: "edit", label: "Edit", icon: Edit },
  { id: "eye", label: "Eye", icon: Eye },
  { id: "file", label: "File", icon: FileText },
  { id: "folder", label: "Folder", icon: Folder },
  { id: "home", label: "Home", icon: Home },
  { id: "image", label: "Image", icon: Image },
  { id: "keyboard", label: "Keyboard", icon: Keyboard },
  { id: "link", label: "Link", icon: Link },
  { id: "lock", label: "Lock", icon: Lock },
  { id: "mail", label: "Mail", icon: Mail },
  { id: "mic", label: "Microphone", icon: Mic },
  { id: "pause", label: "Pause", icon: Pause },
  { id: "play", label: "Play", icon: Play },
  { id: "plus", label: "Add", icon: Plus },
  { id: "refresh", label: "Refresh", icon: RefreshCw },
  { id: "save", label: "Save", icon: Save },
  { id: "scissors", label: "Cut", icon: Scissors },
  { id: "search", label: "Search", icon: Search },
  { id: "settings", label: "Settings", icon: Settings },
  { id: "star", label: "Star", icon: Star },
  { id: "terminal", label: "Terminal", icon: Terminal },
  { id: "trash", label: "Delete", icon: Trash2 },
  { id: "upload", label: "Upload", icon: Upload },
  { id: "user", label: "User", icon: User },
  { id: "volume", label: "Volume", icon: Volume2 },
] as const satisfies readonly {
  id: string;
  label: string;
  icon: LucideIcon;
}[];

export type MacroIconId = (typeof MACRO_ICON_OPTIONS)[number]["id"];

export const getMacroIcon = (id: string | undefined): LucideIcon | null =>
  MACRO_ICON_OPTIONS.find((option) => option.id === id)?.icon ?? null;
